apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
data:
  key: QVFENnNsNWMrQm52T2hBQXVYclJVeVNuUzBhOXVUVk00WnpiVFE9PQ==
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-storage
provisioner: "ceph.com/rbd"
parameters:
  monitors: '192.168.50.32:6789'
  adminId: admin
  adminSecretName: ceph-secret
  pool: redis
  userId: admin
  userSecretName: ceph-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vol-rbd-service
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: vol-rbd-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vol-rbd-pod
  labels:
    app: vol-rbd-pod
spec:
  serviceName: vol-rbd-pod
  selector:
    matchLabels:
      app: vol-rbd-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: vol-rbd-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: vol-rbd-pod
          image: redis:4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redisport
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: redis-rbd-vol
          persistentVolumeClaim:
            claimName: ceph-claim
  volumeClaimTemplates:
    - metadata:
        name: ceph-claim
        annotations:
          volume.beta.kubernetes.io/storage-class: ceph-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
