apiVersion: v1
kind: Secret
metadata:
  name: ceph-redis-secret
type: "kubernetes.io/rbd"
data:
  key: QVFENnNsNWMrQm52T2hBQXVYclJVeVNuUzBhOXVUVk00WnpiVFE9PQ==
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-redis-secret
provisioner: "kubernetes.io/rbd"
parameters:
  monitors: '192.168.50.32:6789'
  adminId: admin
  adminSecretName: ceph-redis-secret
  pool: kube
  userId: admin
  userSecretName: ceph-redis-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vol-rbd-service
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: vol-rbd-pod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vol-rbd-ingress
  labels:
    app: vol-rbd-pod
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: redis.kubernetes.io
      http:
        paths:
          - backend:
              serviceName: vol-rbd-service
              servicePort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vol-rbd-pod
  labels:
    app: vol-rbd-pod
spec:
  serviceName: vol-rbd-pod
  selector:
    matchLabels:
      app: vol-rbd-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: vol-rbd-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: vol-rbd-pod
          image: redis:4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redisport
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: ceph-redis-secret
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
