apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
type: "kubernetes.io/rbd"
data:
  key: QVFENnNsNWMrQm52T2hBQXVYclJVeVNuUzBhOXVUVk00WnpiVFE9PQ==
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: ceph-rbd
provisioner: "kubernetes.io/rbd"
parameters:
  monitors: 192.168.50.32:6789
  adminId: admin
  adminSecretName: ceph-secret
  pool: kube
  userId: admin
  userSecretName: ceph-secret
  image: redis
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
---
apiVersion: v1
kind: Pod
metadata:
  name: vol-rbd-pod
  labels:
    app: vol-rbd-pod
spec:
  containers:
    - name: vol-rbd-pod
      image: redis:4-alpine
      ports:
        - containerPort: 6379
          name: redisport
      volumeMounts:
        - mountPath: /data
          name: redis-rbd-vol
      imagePullPolicy: IfNotPresent
  volumes:
    - name: redis-rbd-vol
      persistentVolumeClaim:
        claimName: ceph-claim
  restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: ceph-rbd
spec:
  accessModes:
    - ReadWriteOne
  resources:
    requests:
      storage: 2Gi