apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  labels:
    app: vol-rbd-pod
type: "kubernetes.io/rbd"
data:
  key: QVFENnNsNWMrQm52T2hBQXVYclJVeVNuUzBhOXVUVk00WnpiVFE9PQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbd-provisioner
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: vol-rbd-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: rbd-provisioner
    spec:
      containers:
        - name: rbd-provisioner
          image: "quay.io/external_storage/rbd-provisioner:latest"
      serviceAccountName: persistent-volume-binder
---
apiVersion: v1
kind: Pod
metadata:
  name: vol-rbd-pod
  labels:
    app: vol-rbd-pod
spec:
  containers:
    - name: vol-rbd-pod
      image: redis:4-alpine
      ports:
        - containerPort: 6379
          name: redisport
      volumeMounts:
        - mountPath: /data
          name: redis-rbd-vol
      imagePullPolicy: IfNotPresent
  volumes:
    - name: redis-rbd-vol
      rbd:
        monitors:
          - '192.168.50.32:6789'
        pool: kube
        image: redis
        fsType: xfs
        readOnly: false
        user: admin
        keyring: /etc/ceph/keyring
        secretRef:
          name: ceph-secret
  restartPolicy: Always
