apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-endpoints
subsets:
  - addresses:
      - ip: gfs01.kubernetes.io
    ports:
      - port: 24007
        name: glusterd
  - addresses:
      - ip: gfs02.kubernetes.io
    ports:
      - port: 24007
        name: glustered
  - addresses:
      - ip: gfs03.kubernetes.io
    ports:
      - port: 24007
        name: glusterd
---
apiVersion: v1
kind: Pod
metadata:
  name: vol-glusterfs-pod
  labels:
    app: vol-glusterfs-pod
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
          name: redisport
      volumeMounts:
        - mountPath: /data
          name: redisdata
      imagePullPolicy: IfNotPresent
  volumes:
    - name: redisdata
      glusterfs:
        endpoints: glusterfs-endpoints
        path: kube-redis
        readOnly: false
  restartPolicy: Always
