apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-app
  labels:
    app: nginx-app
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: nginx-app
              servicePort: 80
